version: '3'

services:
  frontend:
    build: ./frontend
    ports:
      - 8080:2015
    environment:
      PROXY_BFF_HOST: http://bff:3000
    networks:
      - default

  bff:
    build: ./bff
    environment:
      NODE_PORT: 3000
    networks:
      - default

networks:
  default: {}
