version: '3'

services:
  frontend-static:
    build: ./frontend-static
    ports:
      - 8080:2015
    environment:
      PROXY_BFF_HOST: http://bff:3000
    networks:
      - default

  frontend-webpack:
    build: ./frontend-webpack
    ports:
      - 8081:2015
    environment:
      PROXY_BFF_HOST: http://bff:3000
    networks:
      - default

  bff:
    build: ./bff
    networks:
      - default

networks:
  default: {}
